[".local/share/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    clone.args = ["--depth", "1", "-b", "master"]

[".zsh/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    clone.args = ["--depth", "1", "-b", "master"]

[".local/share/nvim/site/pack/packer/start/packer.nvim"]
    type = "git-repo"
    url = "https://github.com/wbthomason/packer.nvim"
    clone.args = ["--depth", "1", "-b", "master"]
