set-option -g default-terminal tmux-256color
# マウス有効化
set -g mouse off

# Ctrl+a をプレフィックスに
set-option -g prefix C-a
unbind C-b
bind C-a send-prefix

# スプリットでの移動を簡単に
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# prefix + \ で垂直分割
bind | split-window -h
# prefix + - で水平分割
bind - split-window -v

# ペインのリサイズ
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# ペインの最大化
bind -n C-z resize-pane -Z

# ウィンドウを切り替える
bind -n S-left previous-window
bind -n S-right next-window

# window-statusの見た目を変更
set -g terminal-overrides 'xterm:colors=256'
setw -g status-style fg=colour255,bg=colour234
setw -g window-status-current-format '#[bg=colour2,fg=colour255] #I #W'
setw -g window-status-format '#[fg=colour242] #I #W'

# マウスを一時的に有効化
bind m set -g mouse off \; display "mouse OFF"
bind M set -g mouse on  \; display "mouse ON"

# ペインのボーダー設定
set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=colour39,bg=colour39
